livy:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/rewrite-target: /$1
    path: /livy/?(.*)
    hosts:
    - my-cluster.example.com
    tls:
    - secretName: spark-cluster-tls
      hosts:
      - my-cluster.example.com
  persistence:
    enabled: true
  env:
    LIVY_LIVY_UI_BASE1PATH: {value: "/livy"}
    # Configure Ingresses for Spark UIs
    LIVY_LIVY_SERVER_KUBERNETES_INGRESS_CREATE: {value: "true"}
    LIVY_LIVY_SERVER_KUBERNETES_INGRESS_PROTOCOL: {value: "https"}
    LIVY_LIVY_SERVER_KUBERNETES_INGRESS_HOST: {value: "my-cluster.example.com"}
    LIVY_LIVY_SERVER_KUBERNETES_INGRESS_TLS_SECRET1NAME: {value: "spark-cluster-tls"}
    LIVY_LIVY_SERVER_KUBERNETES_INGRESS_ADDITIONAL1ANNOTATIONS: {value: "kubernetes.io/tls-acme=true"}

historyserver:
  enabled: false

notebooks:
  examples:
    fromDir: notebooks

jupyterhub:
  enabled: true
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
    hosts:
    - my-cluster.example.com
    pathSuffix: ''
    tls:
    - secretName: spark-cluster-tls
      hosts:
      - my-cluster.example.com
  hub:
    # Set up in addition to ingress
    baseUrl: /jupyterhub
    publicURL: "https://my-cluster.example.com"
    # $> openssl rand -hex 32
    cookieSecret: 41b85e5f50222b1542cc3b38a51f4d744864acca5e94eeb78c6e8c19d89eb433
  proxy:
    # $> openssl rand -hex 32
    secretToken: cc52356e9a19a50861b22e08c92c40b8ebe617192f77edb355b9bf4b74b055de

  singleuser:
    startTimeout: 600
    # nodeSelector:
    #   agentpool: sparkpool
    # extraNodeAffinity:
    #   preferred:
    #   - weight: 10
    #     preference:
    #       matchExpressions:
    #       - key: autoscale-retain
    #         operator: NotIn
    #         values:
    #         - "true"
    # extraEnv:
    #   ENV_NAME: "env-value"
    
    storage:
      capacity: 2Gi
      homeMountPath: /home/jovyan/notebooks
      extraVolumes:
      - name: spark-cluster-notebooks-examples
        configMap:
          name: spark-cluster-notebooks-examples
      extraVolumeMounts:
      - name: spark-cluster-notebooks-examples
        mountPath: /home/jovyan/notebooks/examples
        readOnly: true
    
    image:
      name: sasnouskikh/jupyter
      tag: 4.6.3-sparkmagic_0.15.0
      pullPolicy: Always

    cpu:
      limit: 0.5
      guarantee: 0.25
    memory:
      limit: 2G
      guarantee: 1G

    profileList:
    # https://jupyter-docker-stacks.readthedocs.io/en/latest/using/specifics.html#apache-spark
    - display_name: "Jupyter Notebooks"
      description: "Sparkmagic kernel"
      default: True
      # https://jupyterhub-kubespawner.readthedocs.io/en/latest/spawner.html#kubespawner.KubeSpawner
      kubespawner_override:
        environment:
          # For Sparkmagic Kernel
          LIVY_ENDPOINT: "http://livy-server:80"
        cmd:
        - "/opt/singleuser-entrypoint.sh"
        - "--NotebookApp.notebook_dir=/home/jovyan/notebooks"
    
    # defaultUrl: "/lab"
    # extraTolerations: []
    # nodeSelector: {}
    # extraNodeAffinity:
    #   required: []
    #   preferred: []
    # extraPodAffinity:
    #   required: []
    #   preferred: []
    # extraPodAntiAffinity:
    #   required: []
    #   preferred: []
