apiVersion: v1
appVersion: v0.8.0-incubating-SNAPSHOT
description: Apache Livy server to run Spark on Kubernetes
home: https://livy.incubator.apache.org/
icon: https://livy.incubator.apache.org/assets/themes/apache/img/logo.png
keywords:
- livy
- spark
maintainers:
- email: jahstreetlove@gmail.com
  name: jahstreet
name: livy
sources:
- https://github.com/jahstreet/spark-on-kubernetes-helm/tree/master/charts/livy
- https://github.com/jahstreet/spark-on-kubernetes-docker/tree/master/livy
- https://github.com/apache/incubator-livy/pull/167
version: 2.0.1
